-- ============================================================
-- PORTAL MSA — Persistência anônima de registros
-- Execute este arquivo UMA VEZ no SQL Editor do Supabase.
-- O frontend usa somente RPCs públicas controladas por token anônimo.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.portal_participants (
  participant_id uuid primary key,
  access_token uuid not null unique,
  recovery_code text not null unique,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.portal_records (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.portal_participants(participant_id) on delete cascade,
  module text not null,
  record_type text not null,
  record_key text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(participant_id, module, record_type, record_key)
);

create table if not exists public.portal_events (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.portal_participants(participant_id) on delete cascade,
  module text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ix_portal_records_participant
  on public.portal_records(participant_id, module, record_type);

create index if not exists ix_portal_events_participant
  on public.portal_events(participant_id, module, created_at desc);

alter table public.portal_participants enable row level security;
alter table public.portal_records enable row level security;
alter table public.portal_events enable row level security;

-- Sem acesso direto às tabelas pelo navegador.
revoke all on public.portal_participants from anon, authenticated;
revoke all on public.portal_records from anon, authenticated;
revoke all on public.portal_events from anon, authenticated;
revoke all on sequence public.portal_events_id_seq from anon, authenticated;

-- Helper privado: confirma que participant_id + access_token correspondem.
create or replace function public.portal_assert_participant(
  p_participant_id uuid,
  p_access_token uuid
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.portal_participants p
    where p.participant_id = p_participant_id
      and p.access_token = p_access_token
  ) then
    raise exception 'Identificador de participante inválido'
      using errcode = '42501';
  end if;

  update public.portal_participants
     set last_seen_at = now()
   where participant_id = p_participant_id
     and access_token = p_access_token;
end;
$$;

revoke all on function public.portal_assert_participant(uuid, uuid) from public, anon, authenticated;

-- Registra silenciosamente o navegador na primeira gravação.
create or replace function public.portal_register_participant(
  p_participant_id uuid,
  p_access_token uuid,
  p_recovery_code text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows integer;
begin
  if p_participant_id is null or p_access_token is null then
    raise exception 'Identificador inválido';
  end if;

  if length(trim(coalesce(p_recovery_code,''))) < 15 then
    raise exception 'Código de recuperação inválido';
  end if;

  insert into public.portal_participants(participant_id, access_token, recovery_code)
  values (p_participant_id, p_access_token, upper(trim(p_recovery_code)))
  on conflict (participant_id) do update
     set last_seen_at = now()
   where portal_participants.access_token = excluded.access_token;

  get diagnostics v_rows = row_count;
  if v_rows = 0 then
    raise exception 'Conflito de identificador'
      using errcode = '42501';
  end if;
end;
$$;

-- Upsert do estado atual: atividade, progresso, resposta, tentativa etc.
create or replace function public.portal_upsert_record(
  p_participant_id uuid,
  p_access_token uuid,
  p_module text,
  p_record_type text,
  p_record_key text,
  p_payload jsonb
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  perform public.portal_assert_participant(p_participant_id, p_access_token);

  insert into public.portal_records(
    participant_id, module, record_type, record_key, payload
  )
  values (
    p_participant_id,
    left(coalesce(p_module,''),80),
    left(coalesce(p_record_type,''),80),
    left(coalesce(p_record_key,''),180),
    coalesce(p_payload,'{}'::jsonb)
  )
  on conflict(participant_id,module,record_type,record_key)
  do update set
    payload = excluded.payload,
    updated_at = now()
  returning id into v_id;

  return v_id;
end;
$$;

-- Histórico append-only para auditoria de ações.
create or replace function public.portal_append_event(
  p_participant_id uuid,
  p_access_token uuid,
  p_module text,
  p_event_type text,
  p_payload jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  perform public.portal_assert_participant(p_participant_id, p_access_token);

  insert into public.portal_events(participant_id,module,event_type,payload)
  values (
    p_participant_id,
    left(coalesce(p_module,''),80),
    left(coalesce(p_event_type,''),100),
    coalesce(p_payload,'{}'::jsonb)
  )
  returning id into v_id;

  return v_id;
end;
$$;

-- Recupera somente os registros do participante que conhece o token.
create or replace function public.portal_get_records(
  p_participant_id uuid,
  p_access_token uuid,
  p_module text default null
) returns table (
  module text,
  record_type text,
  record_key text,
  payload jsonb,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.portal_assert_participant(p_participant_id, p_access_token);

  return query
  select r.module, r.record_type, r.record_key, r.payload, r.created_at, r.updated_at
    from public.portal_records r
   where r.participant_id = p_participant_id
     and (p_module is null or r.module = p_module)
   order by r.updated_at desc;
end;
$$;

-- Código de recuperação funciona como credencial bearer.
-- Quem possui o código pode recuperar a jornada.
create or replace function public.portal_recover(
  p_recovery_code text
) returns table (
  participant_id uuid,
  access_token uuid,
  recovery_code text
)
language sql
security definer
set search_path = public
as $$
  select p.participant_id, p.access_token, p.recovery_code
  from public.portal_participants p
  where p.recovery_code = upper(trim(p_recovery_code))
  limit 1;
$$;

revoke all on function public.portal_register_participant(uuid,uuid,text) from public;
revoke all on function public.portal_upsert_record(uuid,uuid,text,text,text,jsonb) from public;
revoke all on function public.portal_append_event(uuid,uuid,text,text,jsonb) from public;
revoke all on function public.portal_get_records(uuid,uuid,text) from public;
revoke all on function public.portal_recover(text) from public;

grant execute on function public.portal_register_participant(uuid,uuid,text) to anon;
grant execute on function public.portal_upsert_record(uuid,uuid,text,text,text,jsonb) to anon;
grant execute on function public.portal_append_event(uuid,uuid,text,text,jsonb) to anon;
grant execute on function public.portal_get_records(uuid,uuid,text) to anon;
grant execute on function public.portal_recover(text) to anon;

-- Opcional: também deixa funcionar caso no futuro exista sessão autenticada.
grant execute on function public.portal_register_participant(uuid,uuid,text) to authenticated;
grant execute on function public.portal_upsert_record(uuid,uuid,text,text,text,jsonb) to authenticated;
grant execute on function public.portal_append_event(uuid,uuid,text,text,jsonb) to authenticated;
grant execute on function public.portal_get_records(uuid,uuid,text) to authenticated;
grant execute on function public.portal_recover(text) to authenticated;
